
export interface Player {
  number: number;
  name: string;
  position: string;
  age: number;
  draft: string;
  category: 'player' | 'coach' | 'staff';
  positionCategory?: 'pitcher' | 'infielder' | 'outfielder' | 'catcher';
}

export const playersData: Player[] = [
  // Main players
  { number: 0, name: '辻本 倫太郎', position: '内野手', age: 25, draft: "'23 3位", category: 'player', positionCategory: 'infielder' },
  { number: 1, name: '岡林 勇希', position: '外野手', age: 24, draft: "'19 5位", category: 'player', positionCategory: 'outfielder' },
  { number: 2, name: '田中 幹也', position: '内野手', age: 26, draft: "'22 6位", category: 'player', positionCategory: 'infielder' },
  { number: 3, name: '高橋 周平', position: '内野手', age: 32, draft: "'11 1位", category: 'player', positionCategory: 'infielder' },
  { number: 4, name: 'O.カリステ', position: '内野手', age: 34, draft: '外国人', category: 'player', positionCategory: 'infielder' },
  { number: 5, name: '村松 開人', position: '内野手', age: 26, draft: "'22 2位", category: 'player', positionCategory: 'infielder' },
  { number: 7, name: '福永 裕基', position: '内野手', age: 30, draft: "'22 7位", category: 'player', positionCategory: 'infielder' },
  { number: 8, name: '大島 洋平', position: '外野手', age: 41, draft: "'09 5位", category: 'player', positionCategory: 'outfielder' },
  { number: 9, name: '石伊 雄太', position: '捕手', age: 25, draft: "'24 4位", category: 'player', positionCategory: 'catcher' },
  { number: 11, name: '中西 聖輝', position: '投手', age: 22, draft: "'25 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 13, name: '橋本 侑樹', position: '投手', age: 28, draft: "'19 2位", category: 'player', positionCategory: 'pitcher' },
  { number: 14, name: '草加 勝', position: '投手', age: 25, draft: "'23 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 16, name: '櫻井 頼之介', position: '投手', age: 22, draft: "'25 2位", category: 'player', positionCategory: 'pitcher' },
  { number: 17, name: '柳 裕也', position: '投手', age: 32, draft: "'16 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 19, name: '高橋 宏斗', position: '投手', age: 24, draft: "'20 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 20, name: '涌井 秀章', position: '投手', age: 40, draft: "'04 1位(西)", category: 'player', positionCategory: 'pitcher' },
  { number: 21, name: '金丸 夢斗', position: '投手', age: 25, draft: "'24 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 22, name: '大野 雄大', position: '投手', age: 38, draft: "'10 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 23, name: 'サノー', position: '内野手', age: 32, draft: '外国人', category: 'player', positionCategory: 'infielder' },
  { number: 24, name: 'J.ボスラー', position: '内野手', age: 32, draft: '外国人', category: 'player', positionCategory: 'infielder' },
  { number: 25, name: '石川 昂弥', position: '内野手', age: 25, draft: "'19 1位", category: 'player', positionCategory: 'infielder' },
  { number: 26, name: '仲地 礼亜', position: '投手', age: 25, draft: "'22 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 29, name: '松木平 優太', position: '投手', age: 24, draft: "'20 育成3位", category: 'player', positionCategory: 'pitcher' },
  { number: 30, name: '根尾 昂', position: '投手', age: 26, draft: "'18 1位", category: 'player', positionCategory: 'pitcher' },
  { number: 31, name: '森 駿太', position: '内野手', age: 23, draft: "'24 3位", category: 'player', positionCategory: 'infielder' },
  { number: 32, name: '伊藤 茉央', position: '投手', age: 26, draft: "'22 4位(楽)", category: 'player', positionCategory: 'pitcher' },
  { number: 34, name: '福 敬登', position: '投手', age: 34, draft: "'15 4位", category: 'player', positionCategory: 'pitcher' },
  { number: 35, name: '木下 拓哉', position: '捕手', age: 35, draft: "'15 2位", category: 'player', positionCategory: 'catcher' },
  { number: 36, name: '福田 幸之介', position: '投手', age: 22, draft: "'23 4位", category: 'player', positionCategory: 'pitcher' },
  { number: 38, name: '松葉 貴大', position: '投手', age: 36, draft: "'12 1位(オ)", category: 'player', positionCategory: 'pitcher' },
  { number: 39, name: '宇佐見 真吾', position: '捕手', age: 33, draft: "'15 4位(巨)", category: 'player', positionCategory: 'catcher' },
  { number: 41, name: '勝野 昌慶', position: '投手', age: 29, draft: "'18 3位", category: 'player', positionCategory: 'pitcher' },
  { number: 42, name: 'ブライト 健太', position: '外野手', age: 27, draft: "'21 1位", category: 'player', positionCategory: 'outfielder' },
  { number: 43, name: '味谷 大誠', position: '捕手', age: 24, draft: "'21 4位", category: 'player', positionCategory: 'catcher' },
  { number: 44, name: '川越 誠司', position: '外野手', age: 33, draft: "'15 2位(西)", category: 'player', positionCategory: 'outfielder' },
  { number: 45, name: '土田 龍空', position: '内野手', age: 24, draft: "'20 3位", category: 'player', positionCategory: 'infielder' },
  { number: 46, name: '梅野 雄吾', position: '投手', age: 27, draft: "'16 3位(ヤ)", category: 'player', positionCategory: 'pitcher' },
  { number: 47, name: '吉田 聖弥', position: '投手', age: 24, draft: "'24 2位", category: 'player', positionCategory: 'pitcher' },
  { number: 48, name: '阿部 寿樹', position: '内野手', age: 37, draft: "'15 5位 (楽より復帰)", category: 'player', positionCategory: 'infielder' },
  { number: 49, name: '加藤 匠馬', position: '捕手', age: 34, draft: "'14 5位", category: 'player', positionCategory: 'catcher' },
  { number: 50, name: '清水 達也', position: '投手', age: 27, draft: "'17 4位", category: 'player', positionCategory: 'pitcher' },
  { number: 51, name: '上林 誠知', position: '外野手', age: 31, draft: "'13 4位(ソ)", category: 'player', positionCategory: 'outfielder' },
  { number: 52, name: '篠﨑 国忠', position: '投手', age: 20, draft: "'25 3位", category: 'player', positionCategory: 'pitcher' },
  { number: 54, name: '藤嶋 健人', position: '投手', age: 28, draft: "'16 5位", category: 'player', positionCategory: 'pitcher' },
  { number: 55, name: '細川 成也', position: '外野手', age: 28, draft: "'16 5位(De)", category: 'player', positionCategory: 'outfielder' },
  { number: 56, name: '新保 茉良', position: '内野手', age: 22, draft: "'25 5位", category: 'player', positionCategory: 'infielder' },
  { number: 57, name: '花田 旭', position: '外野手', age: 22, draft: "'25 6位", category: 'player', positionCategory: 'outfielder' },
  { number: 58, name: '石橋 康太', position: '捕手', age: 26, draft: "'18 4位", category: 'player', positionCategory: 'catcher' },
  { number: 59, name: '齋藤 綱記', position: '投手', age: 27, draft: "'14 5位(オ)", category: 'player', positionCategory: 'pitcher' },
  { number: 60, name: '山本 泰寛', position: '内野手', age: 33, draft: "'15 9位(巨)", category: 'player', positionCategory: 'infielder' },
  { number: 61, name: '高橋 幸佑', position: '投手', age: 23, draft: "'24 5位", category: 'player', positionCategory: 'pitcher' },
  { number: 63, name: '板山 祐太郎', position: '内野手', age: 32, draft: "'15 6位(神)", category: 'player', positionCategory: 'infielder' },
  { number: 64, name: '有馬 惵叶', position: '投手', age: 21, draft: "'24 6位", category: 'player', positionCategory: 'pitcher' },
  { number: 65, name: '知野 直人', position: '内野手', age: 27, draft: "'18 3位(De・現役ドラフト)", category: 'player', positionCategory: 'infielder' },
  { number: 66, name: '鵜飼 航丞', position: '外野手', age: 27, draft: "'21 2位", category: 'player', positionCategory: 'outfielder' },
  { number: 67, name: '能戸 輝夢', position: '外野手', age: 18, draft: "'25 4位", category: 'player', positionCategory: 'outfielder' },
  { number: 69, name: '三浦 瑞樹', position: '投手', age: 27, draft: "'21 育成4位(ソ)", category: 'player', positionCategory: 'pitcher' },
  { number: 90, name: '松山 晋也', position: '投手', age: 26, draft: "'22 育成1位", category: 'player', positionCategory: 'pitcher' },
  { number: 91, name: 'U.メヒア', position: '投手', age: 31, draft: '外国人', category: 'player', positionCategory: 'pitcher' },
  { number: 93, name: 'K.マラー', position: '投手', age: 32, draft: '外国人', category: 'player', positionCategory: 'pitcher' },
  { number: 95, name: 'C.ロドリゲス', position: '内野手', age: 23, draft: '育成昇格', category: 'player', positionCategory: 'infielder' },
  { number: 97, name: '樋口 正修', position: '内野手', age: 28, draft: "'22 育成3位", category: 'player', positionCategory: 'infielder' },
  
  // Coaches
  { number: 71, name: '堂上 直倫', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 72, name: '大野 将太', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 74, name: '飯山 裕志', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 75, name: '小池 正晃', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 76, name: '大塚 晶文', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 77, name: '嶋 基宏', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 78, name: '前田 大輔', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 79, name: '平田 良介', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 80, name: '高山 郁夫', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 81, name: '森越 祐人', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 82, name: '浅尾 拓也', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 83, name: '山井 大介', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 84, name: '福田 永将', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 85, name: '渡邉 博幸', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 86, name: '小林 正人', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 87, name: '中村 豊', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 88, name: '落合 英二', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 89, name: '松中 信彦', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 92, name: '谷 哲也', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 96, name: '藤井 康夫', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 98, name: '田島 慎二', position: 'コーチ', age: 0, draft: '', category: 'coach' },
  { number: 99, name: '井上 一樹', position: '監督', age: 55, draft: '', category: 'staff' },
  { number: 101, name: '赤田 龍一郎', position: 'ブルペン捕手', age: 38, draft: '元中日選手', category: 'staff' },
];

