import type { Player } from "../playerTypes";

export const baystarsPlayers: Player[] = [
  // 投手
  { number: "0", name: "J.デュプランティエ", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "11", name: "東 克樹", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "12", name: "竹田 祐", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "13", name: "伊勢 大夢", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "14", name: "石田 健大", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "15", name: "島田 舜也", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "16", name: "大貫 晋一", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "18", name: "小園 健太", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "19", name: "山﨑 康晃", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "20", name: "坂本 裕哉", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "22", name: "入江 大生", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "24", name: "吉野 光樹", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "27", name: "藤浪 晋太郎", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "30", name: "篠木 健太郎", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "33", name: "武田 陸玖", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "35", name: "橋本 達弥", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "38", name: "松本 凌人", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "39", name: "若松 尚輝", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "41", name: "佐々木 千隼", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "42", name: "A.コックス", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "43", name: "深沢 鳳介", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "45", name: "森原 康平", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "46", name: "坂口 翔颯", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "47", name: "片山 皓心", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "49", name: "J.ルイーズ", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "53", name: "中川 颯", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "54", name: "石田 裕太郎", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "59", name: "平良 拳太郎", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "62", name: "S.レイノルズ", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "64", name: "中川 虎大", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "65", name: "宮城 滝太", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "68", name: "岩田 将貴", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "92", name: "堀岡 隼人", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "98", name: "H.マルセリーノ", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "102", name: "清水 麻成", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "103", name: "金渕 光希", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "111", name: "吉岡 暖", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "115", name: "馬場 皐輔", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "122", name: "庄司 陽斗", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "136", name: "森下 瑠大", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "140", name: "松本 隆之介", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "052", name: "浜地 真澄", position: "投手", age: 0, draft: "", teamId: "baystars", category: "player" },

  // 捕手
  { number: "5", name: "松尾 汐恩", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "10", name: "戸柱 恭孝", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "32", name: "益子 京右", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "50", name: "山本 祐大", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "57", name: "東妻 純平", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "60", name: "古市 尊", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "95", name: "九鬼 隆平", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "127", name: "上甲 凌大", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "130", name: "近藤 大雅", position: "捕手", age: 0, draft: "", teamId: "baystars", category: "player" },

  // 内野手
  { number: "00", name: "林 琢真", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "2", name: "牧 秀悟", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "3", name: "小田 康一郎", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "6", name: "森 敬斗", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "9", name: "京田 陽太", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "25", name: "筒香 嘉智", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "26", name: "三森 大貴", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "31", name: "柴田 竜拓", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "34", name: "宮下 朝陽", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "37", name: "加藤 響", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "44", name: "石上 泰輝", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "48", name: "成瀬 脩人", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "51", name: "宮﨑 敏郎", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "56", name: "田内 真翔", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "66", name: "D.ビシエド", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "125", name: "小笠原 蒼", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "129", name: "西巻 賢二", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "131", name: "清水 詩太", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "193", name: "高見澤 郁魅", position: "内野手", age: 0, draft: "", teamId: "baystars", category: "player" },

  // 外野手
  { number: "4", name: "度会 隆輝", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "7", name: "佐野 恵太", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "8", name: "神里 和毅", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "28", name: "勝又 温史", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "55", name: "井上 絢登", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "58", name: "梶原 昂希", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "61", name: "蝦名 達夫", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "63", name: "関根 大気", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "67", name: "濱 将乃介", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "99", name: "C.ヒュンメル", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
  { number: "155", name: "小針 大輝", position: "外野手", age: 0, draft: "", teamId: "baystars", category: "player" },
];