import type { Player } from "../playerTypes";

export const giantsPlayers: Player[] = [
  // 支配下：投手
  { number: "11", name: "田中 将大", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "15", name: "大勢", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "17", name: "西舘 勇陽", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "19", name: "山﨑 伊織", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "20", name: "戸郷 翔征", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "21", name: "竹丸 和幸", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "26", name: "ウィットリー", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "28", name: "ハワード", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "30", name: "田和 廉", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "31", name: "赤星 優志", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "36", name: "山城 京平", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "41", name: "中川 皓太", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "42", name: "マタ", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "43", name: "則本 昂大", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "45", name: "田中 瑛斗", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "46", name: "又木 鉄平", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "47", name: "森田 駿哉", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "49", name: "バルドナード", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "53", name: "高梨 雄平", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "54", name: "松浦 慶斗", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "56", name: "北浦 竜次", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "57", name: "宮原 駿介", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "58", name: "船迫 大雅", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "62", name: "横川 凱", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "63", name: "泉 圭輔", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "64", name: "山田 龍聖", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "65", name: "石川 達也", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "66", name: "平内 龍太", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "91", name: "堀田 賢慎", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "92", name: "マルティネス", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "97", name: "井上 温大", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 支配下：捕手
  { number: "10", name: "甲斐 拓也", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "22", name: "小林 誠司", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "24", name: "大城 卓三", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "27", name: "岸田 行倫", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "37", name: "郡 拓也", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "67", name: "山瀬 慎之助", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 支配下：内野手
  { number: "00", name: "湯浅 大", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "0", name: "増田 大輝", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "2", name: "吉川 尚輝", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "5", name: "門脇 誠", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "6", name: "坂本 勇人", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "23", name: "石塚 裕惺", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "29", name: "ダルベック", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "32", name: "浦田 俊輔", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "33", name: "小濱 佑斗", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "35", name: "泉口 友汰", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "52", name: "リチャード", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "60", name: "荒巻 悠", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "61", name: "増田 陸", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "99", name: "藤井 健翔", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 支配下：外野手
  { number: "8", name: "丸 佳浩", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "9", name: "松本 剛", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "12", name: "萩尾 匡也", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "13", name: "キャベッジ", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "38", name: "岡田 悠希", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "39", name: "皆川 岳飛", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "40", name: "中山 礼都", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "44", name: "佐々木 俊輔", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "51", name: "浅野 翔吾", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "59", name: "若林 楽人", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "96", name: "三塚 琉生", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 育成：投手
  { number: "011", name: "冨重 英二郎", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "012", name: "林 燦", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "014", name: "堀江 正太郎", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "015", name: "鈴木 圭晋", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "016", name: "千葉 隆広", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "018", name: "木下 幹也", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "019", name: "園田 純規", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "021", name: "松井 颯", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "023", name: "田村 朋輝", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "026", name: "吉村 優聖歩", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "028", name: "富田 龍", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "029", name: "西川 歩", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "030", name: "吹田 志道", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "034", name: "森本 哲星", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "035", name: "ルシアーノ", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "041", name: "黄 錦豪", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "042", name: "グズマン", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "047", name: "河野 優作", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "050", name: "板東 湧梧", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "063", name: "花田 侑樹", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "068", name: "代木 大和", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "077", name: "石田 隼都", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "090", name: "石田 充冴", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "099", name: "京本 眞", position: "投手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 育成：捕手
  { number: "006", name: "松井 蓮太朗", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "020", name: "喜多 隆介", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "022", name: "亀田 啓太", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "024", name: "坂本 達也", position: "捕手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 育成：内野手
  { number: "002", name: "中田 歩夢", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "004", name: "村山 源", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "005", name: "田上 優弥", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "007", name: "宇都宮 葵星", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "025", name: "竹下 徠空", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "027", name: "北村 流音", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "033", name: "平山 功太", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "067", name: "川原田 純平", position: "内野手", age: 0, draft: "", teamId: "giants", category: "player" },

  // 育成：外野手
  { number: "001", name: "鈴木 大和", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "003", name: "知念 大成", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "008", name: "相澤 白虎", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "013", name: "ティマ", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "049", name: "フェリス", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
  { number: "069", name: "笹原 操希", position: "外野手", age: 0, draft: "", teamId: "giants", category: "player" },
];