import type { Player } from "../playerTypes";

export const tigersPlayers: Player[] = [
  {
    number: "3",
    name: "大山 悠輔",
    position: "内野手",
    age: 31,
    draft: "",
    category: "player",
    positionCategory: "infielder",
    teamId: "tigers",
  },
  {
    number: "5",
    name: "近本 光司",
    position: "外野手",
    age: 31,
    draft: "",
    category: "player",
    positionCategory: "outfielder",
    teamId: "tigers",
  },
  {
    number: "8",
    name: "佐藤 輝明",
    position: "内野手",
    age: 26,
    draft: "",
    category: "player",
    positionCategory: "infielder",
    teamId: "tigers",
  },
  {
    number: "2",
    name: "梅野 隆太郎",
    position: "捕手",
    age: 33,
    draft: "",
    category: "player",
    positionCategory: "catcher",
    teamId: "tigers",
  },
  {
    number: "35",
    name: "才木 浩人",
    position: "投手",
    age: 27,
    draft: "",
    category: "player",
    positionCategory: "pitcher",
    teamId: "tigers",
  },
];